apiVersion: apps/v1

kind: Deployment

metadata:
  name: api-server
  labels:
    svc: api-server

spec:
  selector:
    matchLabels:
      svc: api-server
  template:
    metadata:
      labels:
        svc: api-server
    spec:
      containers:
        - name: api-server
          image: 'api-server:v1'

---
apiVersion: v1

kind: Service
metadata:
  name: api-server
  labels:
    svc: api-server

spec:
  ports:
    - port: 8080
  selector:
    svc: api-server
